import { formOptions } from '@tanstack/react-form';
import { z } from 'zod';

export const airExposureStatus = z.enum(['active', 'inactive']);
export const DEDUCTIBLE_TYPES = ['Straight', 'Percentage', 'Franchise', 'Waiting Period'];

export const newAirExposureValues = z.object({
  policyId: z.number().nullable(),
  clientId: z.number().nullable(),
  certificateRef: z.string(),
  locationId: z.string(),
  locationName: z.string().min(1, 'Required'),
  streetAddress: z.string(),
  city: z.string(),
  state: z.string(),
  zipCode: z.string(),
  county: z.string(),
  latitude: z.string(),
  longitude: z.string(),
  geocodeQuality: z.string(),
  numberOfBuildings: z.string(),
  occupancyCode: z.string(),
  constructionCode: z.string(),
  buildingId: z.string(),
  yearBuilt: z.string(),
  numStoreys: z.string(),
  grossFloorArea: z.string(),
  primaryConstructionClass: z.string(),
  roofType: z.string(),
  roofShape: z.string(),
  foundationType: z.string(),
  seismicDesignLevel: z.string(),
  windSpeedDesign: z.string(),
  fireProtectionClass: z.string(),
  sprinkler: z.boolean(),
  unitRef: z.string(),
  unitFloorLevel: z.string(),
  unitGrossArea: z.string(),
  unitOccupancyDesc: z.string(),
  buildingReplacementValue: z.string(),
  contentsValue: z.string(),
  businessInterruptionValue: z.string(),
  deductibleAmount: z.string(),
  deductibleType: z.string(),
  policyLimit: z.string(),
  status: z.string(),
  notes: z.string(),
});
export type NewAirExposureValues = z.infer<typeof newAirExposureValues>;

export const defaultAirExposureValues: NewAirExposureValues = {
  policyId: null,
  clientId: null,
  certificateRef: '',
  locationId: '',
  locationName: '',
  streetAddress: '',
  city: '',
  state: '',
  zipCode: '',
  county: '',
  latitude: '',
  longitude: '',
  geocodeQuality: '',
  numberOfBuildings: '',
  occupancyCode: '',
  constructionCode: '',
  buildingId: '',
  yearBuilt: '',
  numStoreys: '',
  grossFloorArea: '',
  primaryConstructionClass: '',
  roofType: '',
  roofShape: '',
  foundationType: '',
  seismicDesignLevel: '',
  windSpeedDesign: '',
  fireProtectionClass: '',
  sprinkler: false,
  unitRef: '',
  unitFloorLevel: '',
  unitGrossArea: '',
  unitOccupancyDesc: '',
  buildingReplacementValue: '',
  contentsValue: '',
  businessInterruptionValue: '',
  deductibleAmount: '',
  deductibleType: '',
  policyLimit: '',
  status: 'active',
  notes: '',
};

export const newAirExposureFormOpts = formOptions({
  defaultValues: defaultAirExposureValues,
  validators: { onSubmit: newAirExposureValues },
});
