/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as PoliciesNewRouteImport } from './routes/policies.new'
import { Route as AuthPasswordResetRouteImport } from './routes/auth.password-reset'
import { Route as DashboardWorkflowRouteImport } from './routes/_dashboard.workflow'
import { Route as DashboardUsersRouteImport } from './routes/_dashboard.users'
import { Route as DashboardTableRouteImport } from './routes/_dashboard.$table'
import { Route as DashboardTableIndexRouteImport } from './routes/_dashboard.$table.index'
import { Route as DashboardTableIdRouteImport } from './routes/_dashboard.$table.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PoliciesNewRoute = PoliciesNewRouteImport.update({
  id: '/policies/new',
  path: '/policies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasswordResetRoute = AuthPasswordResetRouteImport.update({
  id: '/auth/password-reset',
  path: '/auth/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkflowRoute = DashboardWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTableRoute = DashboardTableRouteImport.update({
  id: '/$table',
  path: '/$table',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTableIndexRoute = DashboardTableIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTableRoute,
} as any)
const DashboardTableIdRoute = DashboardTableIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardTableRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/$table': typeof DashboardTableRouteWithChildren
  '/users': typeof DashboardUsersRoute
  '/workflow': typeof DashboardWorkflowRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/policies/new': typeof PoliciesNewRoute
  '/$table/$id': typeof DashboardTableIdRoute
  '/$table/': typeof DashboardTableIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/users': typeof DashboardUsersRoute
  '/workflow': typeof DashboardWorkflowRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/policies/new': typeof PoliciesNewRoute
  '/': typeof DashboardIndexRoute
  '/$table/$id': typeof DashboardTableIdRoute
  '/$table': typeof DashboardTableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/_dashboard/$table': typeof DashboardTableRouteWithChildren
  '/_dashboard/users': typeof DashboardUsersRoute
  '/_dashboard/workflow': typeof DashboardWorkflowRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/policies/new': typeof PoliciesNewRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/$table/$id': typeof DashboardTableIdRoute
  '/_dashboard/$table/': typeof DashboardTableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/$table'
    | '/users'
    | '/workflow'
    | '/auth/password-reset'
    | '/policies/new'
    | '/$table/$id'
    | '/$table/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/login'
    | '/users'
    | '/workflow'
    | '/auth/password-reset'
    | '/policies/new'
    | '/'
    | '/$table/$id'
    | '/$table'
  id:
    | '__root__'
    | '/_dashboard'
    | '/accept-invite'
    | '/login'
    | '/_dashboard/$table'
    | '/_dashboard/users'
    | '/_dashboard/workflow'
    | '/auth/password-reset'
    | '/policies/new'
    | '/_dashboard/'
    | '/_dashboard/$table/$id'
    | '/_dashboard/$table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
  PoliciesNewRoute: typeof PoliciesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/policies/new': {
      id: '/policies/new'
      path: '/policies/new'
      fullPath: '/policies/new'
      preLoaderRoute: typeof PoliciesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/password-reset': {
      id: '/auth/password-reset'
      path: '/auth/password-reset'
      fullPath: '/auth/password-reset'
      preLoaderRoute: typeof AuthPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/workflow': {
      id: '/_dashboard/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof DashboardWorkflowRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/$table': {
      id: '/_dashboard/$table'
      path: '/$table'
      fullPath: '/$table'
      preLoaderRoute: typeof DashboardTableRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/$table/': {
      id: '/_dashboard/$table/'
      path: '/'
      fullPath: '/$table/'
      preLoaderRoute: typeof DashboardTableIndexRouteImport
      parentRoute: typeof DashboardTableRoute
    }
    '/_dashboard/$table/$id': {
      id: '/_dashboard/$table/$id'
      path: '/$id'
      fullPath: '/$table/$id'
      preLoaderRoute: typeof DashboardTableIdRouteImport
      parentRoute: typeof DashboardTableRoute
    }
  }
}

interface DashboardTableRouteChildren {
  DashboardTableIdRoute: typeof DashboardTableIdRoute
  DashboardTableIndexRoute: typeof DashboardTableIndexRoute
}

const DashboardTableRouteChildren: DashboardTableRouteChildren = {
  DashboardTableIdRoute: DashboardTableIdRoute,
  DashboardTableIndexRoute: DashboardTableIndexRoute,
}

const DashboardTableRouteWithChildren = DashboardTableRoute._addFileChildren(
  DashboardTableRouteChildren,
)

interface DashboardRouteChildren {
  DashboardTableRoute: typeof DashboardTableRouteWithChildren
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardWorkflowRoute: typeof DashboardWorkflowRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardTableRoute: DashboardTableRouteWithChildren,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardWorkflowRoute: DashboardWorkflowRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
  PoliciesNewRoute: PoliciesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
