CREATE TYPE public.clientstatus AS ENUM ('active', 'inactive', 'prospect');
CREATE TYPE public.clienttype AS ENUM ('commercial', 'individual', 'non_profit', 'government');
CREATE TABLE public.clients (id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, company_name character varying, first_name character varying, last_name character varying, client_type public.clienttype, industry character varying NOT NULL, status public.clientstatus DEFAULT 'active'::public.clientstatus NOT NULL, phone character varying, email character varying, address_line1 character varying, address_line2 character varying, city character varying, state character varying, zip character varying, country character varying, updated_at timestamp with time zone DEFAULT now() NOT NULL, date_added date);
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ADD CONSTRAINT clients_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.clients TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.clients TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.clients TO service_role;
