CREATE TYPE public.clientstatus AS ENUM ('active', 'inactive', 'prospect');
CREATE TYPE public.clienttype AS ENUM ('commercial', 'individual', 'non_profit', 'government');

CREATE TABLE public.clients (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,

    -- human-readable reference id (e.g. CLT-2026-0001); see agencies migration for rationale.
    ref_year smallint NOT NULL DEFAULT extract(year from now())::smallint,
    clt_ref varchar(24) GENERATED ALWAYS AS ('CLT-' || ref_year || '-' || lpad(id::text, 5, '0')) STORED UNIQUE,


    company_name varchar(200),
    first_name varchar(100),
    last_name varchar(100),
    client_type public.clienttype,
    industry varchar(100) NOT NULL,
    status public.clientstatus DEFAULT 'active'::public.clientstatus NOT NULL,
    phone varchar(30),
    email varchar(200),

    address_line1 varchar(200),
    address_line2 varchar(200),
    city varchar(100),
    state varchar(2),
    postal varchar(12),
    country varchar(100),
    
    updated_at timestamptz DEFAULT now() NOT NULL, 
    date_added date
);

ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ADD CONSTRAINT clients_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.clients TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.clients TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.clients TO service_role;
