
create type public.app_role as enum ('admin', 'underwriter', 'accounting', 'viewer');

-- USER ROLES
create table public.user_roles (
    id      bigint generated by default as identity primary key,
    user_id uuid references auth.users on delete cascade not null,
    role    app_role not null,
    unique (user_id)
    -- unique (user_id, role)
);
comment on table public.user_roles is 'Application roles for users';

-- ROLE PERMISSIONS
create table public.role_permissions (
    role    app_role not null,
    resource   text not null,          -- table name
    can_read    boolean not null default false,
    can_write    boolean not null default false,
    primary key (role, resource)
);
comment on table public.role_permissions is 'Application permissions for each role';

alter table public.user_roles enable row level security;
alter table public.role_permissions enable row level security;

-- authorize with role-based access control (RBAC)
create function public.authorize(resource text, action text)
returns boolean
language sql stable security definer set search_path = public
as $$
    select coalesce(
        (select case action
                when 'read' then can_read
                when 'write' then can_write
            end
        from public.role_permissions
        where role = (auth.jwt() ->> 'user_role')::public.app_role
            and role_permissions.resource = authorize.resource),
        false);
$$;
