CREATE TYPE public.clientstatus AS ENUM ('active', 'inactive', 'prospect');
CREATE TYPE public.clienttype AS ENUM ('commercial', 'individual', 'non_profit', 'government');

CREATE TABLE public.clients (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    created_at timestamp with time zone DEFAULT now() NOT NULL, 

    company_name varchar(200),
    first_name varchar(100),
    last_name varchar(100),
    client_type public.clienttype,
    industry varchar(100) NOT NULL,
    status public.clientstatus DEFAULT 'active'::public.clientstatus NOT NULL,
    phone varchar(30),
    email varchar(200),

    address_line1 varchar(200),
    address_line2 varchar(200),
    city varchar(100),
    state varchar(2),
    zip varchar(12),
    country varchar(100),
    
    updated_at timestamptz DEFAULT now() NOT NULL, 
    date_added date
);

ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ADD CONSTRAINT clients_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.clients TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.clients TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.clients TO service_role;
